# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Javier Peralta
tagline:          ''
description:      'M.S. In Computer Science at <a href="https://www.cimat.mx/">CIMAT</a>
                  <br /> Software Developer & Machine Learning Enthusiast
                  <br /> <a href="https://twitter.com/nottu1990" target="_blank">@nottu1990</a>.'
url:              http://nottu.github.io
baseurl:          /

author:
  name:           'Javier Peralta'
  url:            https://twitter.com/nottu1990

paginate_multiple:
  - paginate: 3
    paginate_path: '/page:num/'
    sub_dir: '/general'
  - paginate: 3
    paginate_path: '/papers/page:num/'
    sub_dir: '/papers'

# Custom vars
version:          2.1.0

plugins:          [jekyll-paginate, jekyll-gist, jekyll-paginate-multiple]

github:
  repo:           https://github.com/nottu/nottu.github.io
