# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Javier Peralta
tagline:          ''
description:      'M.S. In Computer Science at <a href="https://www.cimat.mx/">CIMAT</a>
                  <br /> Software Developer & Machine Learning Enthusiast
                  <br /> <a href="https://twitter.com/nottu1990" target="_blank">@nottu1990</a>.'
url:              http://nottu.github.io
baseurl:          /

author:
  name:           'Javier Peralta'
  url:            https://twitter.com/nottu1990

paginate:         5

# Custom vars
version:          2.1.0

plugins:          [jekyll-paginate, jekyll-gist]

github:
  repo:           https://github.com/nottu/nottu.github.io
